// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5rl30nRuy5CgrCMiYKoRI22tAFI4AIRE',
    appId: '1:280313789301:web:0dbfedca8b423ac5d3313c',
    messagingSenderId: '280313789301',
    projectId: 'quiz-pln',
    authDomain: 'quiz-pln.firebaseapp.com',
    storageBucket: 'quiz-pln.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRdiccDsCJ-l5DvdLQnCyFSifll064PT0',
    appId: '1:280313789301:android:8b98adb3bafb41d7d3313c',
    messagingSenderId: '280313789301',
    projectId: 'quiz-pln',
    storageBucket: 'quiz-pln.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvioJ945hw44eVONQl8nv9G9zROmq-FVs',
    appId: '1:280313789301:ios:6f41ecaf22a9f099d3313c',
    messagingSenderId: '280313789301',
    projectId: 'quiz-pln',
    storageBucket: 'quiz-pln.firebasestorage.app',
    iosBundleId: 'com.example.quizPlnGen2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvioJ945hw44eVONQl8nv9G9zROmq-FVs',
    appId: '1:280313789301:ios:6f41ecaf22a9f099d3313c',
    messagingSenderId: '280313789301',
    projectId: 'quiz-pln',
    storageBucket: 'quiz-pln.firebasestorage.app',
    iosBundleId: 'com.example.quizPlnGen2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5rl30nRuy5CgrCMiYKoRI22tAFI4AIRE',
    appId: '1:280313789301:web:8c2502dd8b4dfa15d3313c',
    messagingSenderId: '280313789301',
    projectId: 'quiz-pln',
    authDomain: 'quiz-pln.firebaseapp.com',
    storageBucket: 'quiz-pln.firebasestorage.app',
  );
}
